### ISSUE TITLE
how to use it in yolov5？

### ISSUE THREAD

**Issue by ZeWu0307** [USTC-MrHang/yolov5_NMS-Soft-NMS#1]
l want to know how to use it and add it to the code of yolov5，please.

**Comment by yyvhang** [comment]
just use function:self_soft_nms to change utils/genera.py
line 754 i = torchvision.ops.nms(boxes, scores, iou_thres) 
to 
i = Self_Soft_NMS(boxes, scores, iou_thres, False, False, False, 0, 0.5, 0.01)
